from selenium import webdriver
import time
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
import selenium

class DRmodles:
    button_models_xpath="//span[contains(text(),'Models')]"
    tab_available_model_xpath="//div[@id='mat-tab-label-10-0']"
    tab_Create_model_xpath="//span[contains(text(),'create new model')]"
    checkbox_personal_xpath="//div[@class='sub-content py-4']/div/div[2]/div/div[1]/div/div/div/input"
    checkbox_pooled_xpath="//div[@class='sub-content py-4']/div/div[2]/div/div[2]/div/div/div/input"
    description_personal_xpath="//div[@class='sub-content py-4']/div/div[2]/div/div[1]/div/button"
    description_pool_xpath="//div[@class='sub-content py-4']/div/div[2]/div/div[2]/div/button"
    d_checkbox_GPU_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div/div/input"
    d_button_NcSeries_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[3]/div/div[1]/button"
    d_button_NvSeries_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[3]/div/div[2]/button"
    d_dropDown_Region_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[2]/div/select"
    d_category_GP_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[3]/div/div[1]"
    d_category_CO_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[3]/div/div[2]"
    d_category_Burstable_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[3]/div/div[3]"
    d_dropDown_vmInstance_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[4]/div/select"
    d_dropDown_StorageType_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[5]/div/select"
    d_dropDown_StorageSize_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[6]/div/select"
    d_dropDown_ImageLibrary_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[7]/div/select"
    d_dropDown_modelprice_xpath="//div[@class='p-4 ng-star-inserted']/div[5]/div/div[2]/div/div[1]/div/select"
    d_dropDown_Currency_xpath="//div[@class='p-4 ng-star-inserted']/div[5]/div/div[2]/div/div[2]/div/select"
    d_textbox_name_xpath="//div[@class='p-4 ng-star-inserted']/div[6]/div/div[2]/form/div[1]/div/input"
    d_textbox_description_xpath="//div[@class='p-4 ng-star-inserted']/div[6]/div/div[2]/form/div[2]/div/textarea"
    d_dropdown_DesktopPriceShared_xpath="//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[1]/div[1]/select"
    d_dropdown_DesktopPriceDedicated_xpath="//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[2]/div[1]/select"
    d_textdox_SharedDescription_xpath="//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[1]/div[2]/input"
    d_textdox_DedicatedDescription_xpath="//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[2]/div[2]/input"
    d_button_createModel_xpath="//div[@class='p-4 ng-star-inserted']/div[8]/button"
    p_dropDown_Region_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[1]/div/select"
    p_category_GP_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[2]/div/div[1]/button"
    p_category_CO_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[2]/div/div[2]/button"
    p_category_Burstable_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[2]/div/div[3]/button"
    p_dropDown_vmInstance_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[3]/div/select"
    p_MaxUser_Descount_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[4]/div/i[1]"
    p_MaxUser_Inccount_xpath="//div[@class='sub-content py-4'][2]/div/div[2]/form/div[4]/div/i[2]"
    p_dropDown_StorageType_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[5]/div/select"
    p_dropDown_StorageSize_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[6]/div/select"
    p_dropDown_ImageLibrary_xpath = "//div[@class='sub-content py-4'][2]/div/div[2]/form/div[7]/div/select"
    p_dropDown_modelprice_xpath = "//div[@class='p-4 ng-star-inserted']/div[5]/div/div[2]/div/div[1]/div/select"
    p_dropDown_Currency_xpath = "//div[@class='p-4 ng-star-inserted']/div[5]/div/div[2]/div/div[2]/div/select"
    p_textbox_name_xpath = "//div[@class='p-4 ng-star-inserted']/div[6]/div/div[2]/form/div[1]/div/input"
    p_textbox_description_xpath = "//div[@class='p-4 ng-star-inserted']/div[6]/div/div[2]/form/div[2]/div/textarea"
    p_dropdown_DesktopPriceShared_xpath = "//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[1]/div[1]/select"
    p_dropdown_DesktopPriceDedicated_xpath = "//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[2]/div[1]/select"
    p_textdox_SharedDescription_xpath = "//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[1]/div[2]/input"
    p_textdox_DedicatedDescription_xpath = "//div[@class='p-4 ng-star-inserted']/div[7]/div/div[2]/div[2]/div[2]/input"
    p_button_createModel_xpath = "//div[@class='p-4 ng-star-inserted']/div[8]/button"
    anunta_support_xpath="//a[contains(text(),'Anunta Support')]"

